'use client';
import '../globals.css';
// import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//  title: 'FavoriteFlower | Login',
//  description: 'Generated by Next.js',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
 return (
  <html lang='en'>
   <head>
    <title>FavoriteFlower | Login</title>
    <meta name='description' content='Generated by Next.js' />
   </head>
   <body className={inter.className}>
    <SessionProvider>
     <main className='h-screen flex justify-center items-center'>{children}</main>
    </SessionProvider>
   </body>
  </html>
 );
}
