'use client';
import '../globals.css';
import { Inter } from 'next/font/google';
import Sidebar from '@/components/Sidebar';
import { SessionProvider } from 'next-auth/react';
import { Provider } from 'react-redux';
import store from '@/lib/store/store';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
 return (
  <html lang='en'>
   <head>
    <title>Dashboard Admin</title>
    <meta name='description' content='Generated by Next.js' />
   </head>
   <body className={inter.className}>
    <SessionProvider>
     <Provider store={store}>
      <Sidebar />
      <main className='flex flex-col md:flex-row md:justify-between'>
       <div className='md:w-3/4 lg:w-full'>{children}</div>
       {/* <main>{children}</main> */}
      </main>
     </Provider>
    </SessionProvider>
   </body>
  </html>
 );
}
